name: "DLNA"
guid: "33EBA9CD-7DA1-4720-967F-DD7DAE7B74A1"
imageUrl: ""
version: 9
targetAbi: "10.10.7.0"
framework: "net8.0"
owner: "jellyfin"
overview: "DLNA Service"
description: >
  Adds DLNA capability to Jellyfin

category: "General"
artifacts:
  - "Jellyfin.Plugin.Dlna.dll"
  - "Jellyfin.Plugin.Dlna.Model.dll"
  - "Jellyfin.Plugin.Dlna.Playback.dll"
  - "Rssdp.dll"
changelog: |-
  - fix resolution for ts (#146) @tomty89
  - Fix typo in client discovery interval help text (#149) @AnAnalogGuy
  - Strip URL parameters (#137) @Vebryn
